# Generated by Django 6.0.7 on 2026-07-16 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('commission_share', models.DecimalField(decimal_places=2, max_digits=4)),
                ('monthly_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Apartment', 'apartment'), ('Plot', 'plot'), ('Villa', 'villa'), ('Land', 'land'), ('Commercial', 'commercial')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('images', models.ImageField(upload_to='properties')),
                ('status', models.CharField(choices=[('Available', 'available'), ('Sold', 'sold')], default='Available', max_length=255)),
                ('listing_at', models.DateTimeField(auto_now_add=True)),
                ('sqft', models.PositiveIntegerField()),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('source', models.CharField(choices=[('Website', 'website'), ('Walkin', 'walkin'), ('Social Media', 'social_media'), ('Agent', 'agent')], max_length=255)),
                ('min_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('New', 'new'), ('Contacted', 'contacted'), ('Site Visited', 'site_visited'), ('Negotiation', 'negotiation'), ('Lost', 'lost'), ('Done', 'done')], max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='core.agent')),
                ('interested_property_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Cancelled', 'cancelled'), ('Done', 'done')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_closing_date', models.DateField()),
                ('actual_closing_date', models.DateField()),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.lead')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.property')),
            ],
        ),
    ]
