# Generated by Django 6.0.7 on 2026-07-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Cancelled', 'cancelled'), ('Done', 'done')], default='Pending', max_length=255),
        ),
    ]
