# Generated by Django 6.0.7 on 2026-07-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='actual_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
