# Generated by Django 6.0.7 on 2026-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_deal_actual_closing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Done', 'Done')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Website', 'Website'), ('Walkin', 'Walkin'), ('Social Media', 'Social Media'), ('Agent', 'Agent')], max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('Site Visited', 'Site Visited'), ('Negotiation', 'Negotiation'), ('Lost', 'Lost'), ('Done', 'Done')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('plot', 'Plot'), ('villa', 'Villa'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=255),
        ),
    ]
