# Generated by Django 6.0.7 on 2026-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_images_property_image_alter_deal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile'),
        ),
    ]
